## 常用的numpy导入

In [8]:
import numpy as np

### 1 array函数

#### ①np.array(list)  创建数组

In [9]:
#创建一维数组
x = np.array([1,2,3,4,5,6,7])

In [10]:
x

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
#创建二维数组
X = np.array([
                [1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]
            ])

In [12]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### ②探究数组的变量属性

In [13]:
#一维数组x的shape变量
x.shape

(7,)

In [14]:
#二维数组X的shape变量
X.shape

(3, 4)

In [17]:
#一维数组维度
x.ndim

1

In [18]:
#二维数组维度
X.ndim

2

In [22]:
#数据类型
x.dtype

dtype('int32')

In [23]:
#数据类型
X.dtype

dtype('int32')

### 2 arange函数

#### ①np.arange(num)  创建从0到9的数组

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### ②np.arange(start,end,step)  输入从start到end的指定数组，步长为step(步长默认值为1)

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### 3 ones函数

#### ①np.ones(num)  输入从0到指定数字num的整数数组